### ISSUE TITLE
Consider using denite.nvim for neovim users

### ISSUE THREAD

**Issue by dentuzhik** [yardnsm/vim-import-cost#17] opened 2018-10-22 07:59 UTC
This should be a bit prettier than use a split (is this even a split)?
https://github.com/Shougo/denite.nvim

Example of plugin where it is used:
https://github.com/neoclide/npm.nvim

**Comment by yardnsm** [comment] 2018-10-22 13:14
Duplicate of https://github.com/yardnsm/vim-import-cost/issues/16 (probably because of the consistency issue with Github? https://blog.github.com/2018-10-21-october21-incident-report/)

**Closed by yardnsm** 2018-10-22 13:14 UTC
